---
? ''
: - ttl: 1800
    type: MX
    value:
      exchange: inbound-smtp.eu-west-1.amazonaws.com
      preference: 10
  - ttl: 172800
    type: NS
    values:
    - ns-1422.awsdns-49.org.
    - ns-2000.awsdns-58.co.uk.
    - ns-58.awsdns-07.com.
    - ns-597.awsdns-10.net.
  - ttl: 942942942
    type: Route53Provider/ALIAS
    value:
      evaluate-target-health: false
      hosted-zone-id: Z32O12XQLNTSW2
      name: dualstack.moj-produ-elbprodp-d2ropjs5u0fk-1944873465.eu-west-1.elb.amazonaws.com.
      type: A
  - ttl: 300
    type: TXT
    value: v=spf1 ~all
_amazonses:
  ttl: 1800
  type: TXT
  value: zicm2kD310ehPMckMOlRhZTHY3qdTuks7QeS1pvsFCQ=
_dmarc:
  type: TXT
  value: v=DMARC1\; p=none\; sp=none\; pct=100\; fo=1\; ri=3600\; rua=mailto:b966d0e9@inbox.ondmarc.com,mailto:dmarc-rua@dmarc.service.gov.uk,mailto:dmarc@digitaljustice.gov.uk\;
    ruf=mailto:b966d0e9@inbox.ondmarc.com,mailto:dmarc-ruf@dmarc.service.gov.uk\;
csbmua7q2zisva47u7qntezbcut2l2xp._domainkey:
  ttl: 1800
  type: CNAME
  value: csbmua7q2zisva47u7qntezbcut2l2xp.dkim.amazonses.com
w67ooaipewybj4wl2vlnbaf2dgbhe3dq._domainkey:
  ttl: 1800
  type: CNAME
  value: w67ooaipewybj4wl2vlnbaf2dgbhe3dq.dkim.amazonses.com
xlvio4g54tcwne2o7xp644bgwkydfdh7._domainkey:
  ttl: 1800
  type: CNAME
  value: xlvio4g54tcwne2o7xp644bgwkydfdh7.dkim.amazonses.com
