---
? ''
: - ttl: 172800
    type: NS
    values:
    - ns-1392.awsdns-46.org.
    - ns-1913.awsdns-47.co.uk.
    - ns-448.awsdns-56.com.
    - ns-658.awsdns-18.net.
  - ttl: 942942942
    type: Route53Provider/ALIAS
    value:
      evaluate-target-health: false
      hosted-zone-id: Z32O12XQLNTSW2
      name: tribunals-nginx-1184258455.eu-west-1.elb.amazonaws.com.
      type: A
_asvdns-17721b66-624a-4c3e-b95e-bc7aa655b17b:
  ttl: 300
  type: TXT
  value: asvdns_5b959c39-219c-4755-a21b-17ec3dce6ffe
_dmarc:
  ttl: 300
  type: TXT
  value: v=DMARC1\;p=reject\;sp=reject\;rua=mailto:dmarc-rua@dmarc.service.gov.uk\;
www:
  ttl: 942942942
  type: Route53Provider/ALIAS
  value:
    evaluate-target-health: false
    hosted-zone-id: Z32O12XQLNTSW2
    name: tribunals-nginx-1184258455.eu-west-1.elb.amazonaws.com.
    type: A
