---
? ''
: - ttl: 300
    type: CAA
    values:
    - flags: 0
      tag: iodef
      value: mailto:certificates@digital.justice.gov.uk
    - flags: 0
      tag: issue
      value: ;
  - ttl: 300
    type: MX
    value:
      exchange: .
      preference: 0
  - ttl: 172800
    type: NS
    values:
    - ns-1218.awsdns-24.org.
    - ns-2004.awsdns-58.co.uk.
    - ns-777.awsdns-33.net.
    - ns-86.awsdns-10.com.
  - ttl: 300
    type: TXT
    value: v=spf1 -all
'*._domainkey':
  ttl: 300
  type: TXT
  value: v=DKIM1\; p=
_dmarc:
  ttl: 300
  type: TXT
  value: v=DMARC1\;p=reject\;sp=reject\;rua=mailto:dmarc-rua@dmarc.service.gov.uk\;
