---
? ''
: - ttl: 172800
    type: NS
    values:
    - ns-1499.awsdns-59.org.
    - ns-1744.awsdns-26.co.uk.
    - ns-461.awsdns-57.com.
    - ns-879.awsdns-45.net.
  - ttl: 942942942
    type: Route53Provider/ALIAS
    value:
      evaluate-target-health: false
      hosted-zone-id: Z32O12XQLNTSW2
      name: tribunals-nginx-1184258455.eu-west-1.elb.amazonaws.com.
      type: A
_asvdns-226cd46f-ff5e-484f-8c2c-9bd96dbc3b9a:
  ttl: 300
  type: TXT
  value: asvdns_8e89fa64-7341-4517-b63e-7c0f994b95bc
_dmarc:
  ttl: 300
  type: TXT
  value: v=DMARC1\;p=reject\;sp=reject\;rua=mailto:dmarc-rua@dmarc.service.gov.uk\;
www:
  ttl: 942942942
  type: Route53Provider/ALIAS
  value:
    evaluate-target-health: false
    hosted-zone-id: Z32O12XQLNTSW2
    name: tribunals-nginx-1184258455.eu-west-1.elb.amazonaws.com.
    type: A
