---
? ''
: - ttl: 300
    type: CAA
    values:
    - flags: 0
      tag: iodef
      value: mailto:certificates@digital.justice.gov.uk
    - flags: 0
      tag: issue
      value: ;
  - ttl: 300
    type: MX
    value:
      exchange: .
      preference: 0
  - ttl: 172800
    type: NS
    values:
    - ns-116.awsdns-14.com.
    - ns-1415.awsdns-48.org.
    - ns-1665.awsdns-16.co.uk.
    - ns-721.awsdns-26.net.
  - ttl: 300
    type: TXT
    value: v=spf1 -all
'*._domainkey':
  ttl: 300
  type: TXT
  value: v=DKIM1\; p=
_dmarc:
  ttl: 300
  type: TXT
  value: v=DMARC1\;p=reject\;sp=reject\;rua=mailto:dmarc-rua@dmarc.service.gov.uk\;
