---
? ''
: ttl: 172800
  type: NS
  values:
  - ns-1312.awsdns-36.org.
  - ns-2031.awsdns-61.co.uk.
  - ns-469.awsdns-58.com.
  - ns-803.awsdns-36.net.
_bec7b6a29ca37a0129b2033111e16a61.mta-sts:
  ttl: 60
  type: CNAME
  value: _9d4ff3184451a4b050bbfa16a32b366d.bkngfjypgb.acm-validations.aws.
_mta-sts:
  ttl: 300
  type: TXT
  value: v=STSv1\; id=834d3731a4b58170e23b29bae11ad2ab
_smtp._tls:
  ttl: 300
  type: TXT
  value: v=TLSRPTv1\;rua=mailto:tls-rua@mailcheck.service.ncsc.gov.uk
mta-sts:
  ttl: 942942942
  type: Route53Provider/ALIAS
  value:
    evaluate-target-health: true
    hosted-zone-id: Z2FDTNDATAQYW2
    name: d3s1p7nop9zosl.cloudfront.net.
    type: A
