---
? ''
: - ttl: 300
    type: CAA
    values:
    - flags: 0
      tag: iodef
      value: mailto:certificates@digital.justice.gov.uk
    - flags: 0
      tag: issue
      value: ;
  - ttl: 300
    type: MX
    value:
      exchange: .
      preference: 0
  - ttl: 172800
    type: NS
    values:
    - ns-1426.awsdns-50.org.
    - ns-1876.awsdns-42.co.uk.
    - ns-390.awsdns-48.com.
    - ns-645.awsdns-16.net.
  - ttl: 300
    type: TXT
    value: v=spf1 -all
'*._domainkey':
  ttl: 300
  type: TXT
  value: v=DKIM1\; p=
_dmarc:
  ttl: 300
  type: TXT
  value: v=DMARC1\;p=reject\;sp=reject\;rua=mailto:dmarc-rua@dmarc.service.gov.uk\;
