---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config
    default_ttl: 3600
    enforce_order: True
  route53:
    class: octodns.provider.route53.Route53Provider

zones:
  kube.dsd.io.:
    sources:
      - route53

