---
providers:
  yaml:
    class: octodns.provider.yaml.YamlProvider
    directory: ./output
    default_ttl: 3600
    enforce_order: True
  route53:
    class: octodns.provider.route53.Route53Provider

zones:
  kube.dsd.io.:
    sources:
      - route53
    targets:
      - yaml
#  justice.gov.uk.:
#    sources:
#      - route53
#    targets:
#      - yaml
