---
? ''
: - ttl: 172800
    type: NS
    values:
    - ns-1474.awsdns-56.org.
    - ns-1981.awsdns-55.co.uk.
    - ns-470.awsdns-58.com.
    - ns-622.awsdns-13.net.
  - ttl: 942942942
    type: Route53Provider/ALIAS
    value:
      evaluate-target-health: false
      hosted-zone-id: Z32O12XQLNTSW2
      name: tribunals-nginx-1184258455.eu-west-1.elb.amazonaws.com.
      type: A
_dmarc:
  ttl: 300
  type: TXT
  value: v=DMARC1\;p=reject\;sp=reject\;rua=mailto:dmarc-rua@dmarc.service.gov.uk\;
www:
  ttl: 942942942
  type: Route53Provider/ALIAS
  value:
    evaluate-target-health: false
    hosted-zone-id: null
    name: ''
    type: A
