---
? ''
: ttl: 172800
  type: NS
  values:
  - ns-136.awsdns-17.com.
  - ns-1496.awsdns-59.org.
  - ns-1634.awsdns-12.co.uk.
  - ns-557.awsdns-05.net.
www:
  ttl: 300
  type: CNAME
  value: newfuturesnetwork.gov.uk
