---
? ''
: ttl: 172800
  type: NS
  values:
  - ns-1348.awsdns-40.org.
  - ns-1856.awsdns-40.co.uk.
  - ns-323.awsdns-40.com.
  - ns-770.awsdns-32.net.
_dmarc:
  ttl: 300
  type: TXT
  value: v=DMARC1\;p=reject\;sp=reject\;rua=mailto:dmarc-rua@dmarc.service.gov.uk\;
