---
? ''
: - ttl: 60
    type: A
    value: 34.250.68.97
  - ttl: 172800
    type: NS
    values:
    - ns-126.awsdns-15.com.
    - ns-1434.awsdns-51.org.
    - ns-1894.awsdns-44.co.uk.
    - ns-695.awsdns-22.net.
www:
  ttl: 60
  type: A
  value: 34.250.68.97
