---
? ''
: - ttl: 300
    type: A
    value: 34.248.250.65
  - ttl: 172800
    type: NS
    values:
    - ns-1509.awsdns-60.org.
    - ns-1777.awsdns-30.co.uk.
    - ns-294.awsdns-36.com.
    - ns-526.awsdns-01.net.
35llr7vvjyf2asxtmocaafslyojqgoy2._domainkey:
  ttl: 1800
  type: CNAME
  value: 35llr7vvjyf2asxtmocaafslyojqgoy2.dkim.amazonses.com
_amazonses:
  ttl: 1800
  type: TXT
  value: L/PeLeL0Dz/1VizR84If1wvaZZ+aX+k82jhasJFcOkQ=
www:
  ttl: 300
  type: A
  value: 34.248.250.65
xizfpml5z6ivwvzswinpibwt7t36kttr._domainkey:
  ttl: 1800
  type: CNAME
  value: xizfpml5z6ivwvzswinpibwt7t36kttr.dkim.amazonses.com
zkv46ehpqkfqxfbpr6reap6fmibkxmvm._domainkey:
  ttl: 1800
  type: CNAME
  value: zkv46ehpqkfqxfbpr6reap6fmibkxmvm.dkim.amazonses.com
