name: Print out empty hosted zones # A hosted zone with only an NS and SOA record

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  check-for-empty-zones:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python 3.11
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          make install

      - name: Run check for unmanaged zones
        id: check-zones
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.OCTODNS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OCTODNS_AWS_SECRET_ACCESS_KEY }}
          PYTHONUNBUFFERED: 1
        run: make check-empty-zones

      - name: Display results
        run: |
          echo "${{ steps.check-zones.outputs.result }}"
          exit ${{ steps.check-zones.outputs.exit_code }}
