name: SCA
run-name: SCA

on:
  schedule:
    - cron: "0 0 * * 1" # Weekly Monday midnight UTC
  pull_request:
    branches: ["**"]
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  sca:
    name: Software Composition Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      actions: read
      contents: write
      issues: write
      pull-requests: write
      security-events: write

    steps:
      - name: Run SCA
        uses: ministryofjustice/devsecops-actions/sca@9af7935ef39312305084f720326ffb0e6779b1d8 # v1.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          renovate: "false"
          codeql-languages: "python"
          codeql-upload-findings: "always"
