name: OctoDNS Sync

on:
  workflow_dispatch:
  push:
    paths:
      - "hostedzones/**"
      - "config.yaml"
    branches:
      - main

permissions: {}

jobs:
  sync-with-route53:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python 3.11
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          make install

      - name: Run OctoDNS sync
        run: |
          pipenv run make sync-apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.OCTODNS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OCTODNS_AWS_SECRET_ACCESS_KEY }}
