name: OctoDNS Dry Run

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "hostedzones/**"
      - "config.yaml"
    branches:
      - main

jobs:
  dry-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          make install

      - name: Run OctoDNS dry run
        run: |
          pipenv run make sync-dry-run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.OCTODNS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OCTODNS_AWS_SECRET_ACCESS_KEY }}
