name: Run Tests

on:
  push:
    paths:
      - "**.py"
  pull_request:
    paths:
      - "**.py"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pipenv"

      - name: Install Pipenv
        run: pip install pipenv

      - name: Verify Pipfile.lock is in sync
        run: pipenv verify

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run check for unmanaged zones
        id: check-zones
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.OCTODNS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OCTODNS_AWS_SECRET_ACCESS_KEY }}
          PYTHONUNBUFFERED: 1
        run: pipenv test
