name: Run Tests

on:
  push:
    paths:
      - "**.py"
  pull_request:
    paths:
      - "**.py"

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Python 3.11
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          make install

      - name: Run tests
        run: |
          make test
